server:
  port: 8080
  context-path: '/camel'

camel:
  springboot:
    # The Camel context name
    name: ServicesRest

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

# The application configuration properties
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s

spring:
  main:
    banner-mode: "off"
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:tms;MODE=PostgreSQL

  # Spring Data JPA configuration
  jpa:
    hibernate:
      # To be updated in real production usage!
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

logging:
  level:
    org:
      springframework: ERROR
      hibernate:
        type: trace
        stat: debug