server:
  port: 8086
  servlet:
    context-path: /api

spring:
  main:
    banner-mode: "off"
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:cs;MODE=PostgreSQL

logging:
  level:
    org:
      springframework: ERROR
